# To create a secret from an existing kubeconfig, run:
# oc create secret generic kconfig --from-file=config.json=namespacecreate-kubeconfig.yaml -n ansible-tower
apiVersion: v1
kind: Pod
metadata:
  namespace: ansible-tower
spec:
  containers:
    - image: 'quay.io/canit0/ee-custom-container:0.0.1'
      tty: true
      stdin: true
      imagePullPolicy: Always
      args:
        - sleep
        - infinity
      volumeMounts:
      - name: kubeconfig
        mountPath: /home/runner/.kube/config.json
        subPath: config.json
        readOnly: true
  volumes:
  - name: kubeconfig
    secret:
      secretName: kconfig
