---
version: 1

dependencies:
  galaxy: requirements-ee.yml
  python: requirements-ee.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools bindep
  append:
    - RUN alternatives --set python /usr/bin/python3
    - RUN pip install ansible==2.9.7
