apiVersion: v1
kind: Template
metadata:
  name: execution-environment-template
objects:
- apiVersion: v1
  kind: Namespace
  metadata: 
    name: ansible-tower
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: tower
    namespace: ansible-tower
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: pod-manager
    namespace: ansible-tower
  rules:
    - verbs:
        - get
        - list
        - watch
        - create
        - update
        - patch
        - delete
      apiGroups:
        - ''
      resources:
        - pods
    - verbs:
        - create
      apiGroups:
        - ''
      resources:
        - pods/exec
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ansible-tower
    namespace: ansible-tower
  subjects:
    - kind: ServiceAccount
      name: tower
      namespace: ansible-tower
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-manager
