---
version: 1

build_arg_defaults:
  #EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-20-early-access/ee-minimal-rhel8'
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8'

dependencies:
  galaxy: requirements-ee.yml
  python: requirements-ee.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools bindep
  append:
    - RUN alternatives --set python /usr/bin/python3
